#!/bin/bash

deploy_gdal() {
    VERSION=$1
    
    # workspace directory
    workspace="$(mktemp -d)"

    # output directory
    output="$(mktemp -d)"

    # build and package gdal
    pushd $workspace

    curl http://download.osgeo.org/gdal/$VERSION/gdal-$VERSION.tar.gz -s -o - | tar zxf -
    pushd gdal-$VERSION
    ./configure --prefix=$output --without-jasper --with-libkml="/app/.heroku-geo-buildpack/vendor"
    make
    make install

    pushd $output
    tar -czf GDAL-$VERSION.tar.gz *

    if [[ $S3_BUCKET && $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY ]]; then
        aws s3 cp --acl public-read GDAL-$VERSION.tar.gz s3://$S3_BUCKET/$STACK/GDAL/
    fi
}