#!/bin/bash

VERSION=$1

if [ "$VERSION" == "" ]; then
  echo "You must pass desired version of GDAL"
  exit 1
fi

# workspace directory
workspace="$(mktemp -d)"

# output directory
output="$(mktemp -d)"

# build and package gdal
pushd $workspace
curl http://download.osgeo.org/gdal/$VERSION/gdal-$VERSION.tar.gz -s -o - | tar zxf -
pushd GDAL-$VERSION
./configure --prefix=$output
make
make install

pushd $output
tar -czf GDAL-$VERSION.tar.gz *

if [[ $S3_BUCKET && $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY ]]; then
    aws s3 cp GDAL-$VERSION.tar.gz s3://$S3_BUCKET/$STACK/GDAL/
fi
