#!/bin/bash

VERSION=$1

if [ "$VERSION" == "" ]; then
  echo "You must pass desired version of GEOS"
  exit 1
fi

# workspace directory
workspace="$(mktemp -d)"

# output directory
output="$(mktemp -d)"

# build and package geos
pushd $workspace
curl http://download.osgeo.org/geos/geos-$VERSION.tar.bz2 -s -o - | tar xjf -
pushd geos-$VERSION
./configure --prefix=$output
make
make install

pushd $output
tar -czf GEOS-$VERSION.tar.gz *

if [[ $S3_BUCKET && $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY ]]; then
    aws s3 cp --acl public-read GEOS-$VERSION.tar.gz s3://$S3_BUCKET/$STACK/GEOS/
fi
