#!/bin/bash

deploy_proj() {
    VERSION=$1
    
    # workspace directory
    workspace="$(mktemp -d)"

    # output directory
    output="$(mktemp -d)"

    # build and package proj
    pushd $workspace
    curl http://download.osgeo.org/proj/proj-$VERSION.tar.gz -s -o - | tar zxf -
    pushd proj-$VERSION
    ./configure --prefix=$output
    make
    make install

    pushd $output
    tar -czf PROJ-$VERSION.tar.gz *

    if [[ $S3_BUCKET && $AWS_ACCESS_KEY_ID && $AWS_SECRET_ACCESS_KEY ]]; then
        aws s3 cp --acl public-read PROJ-$VERSION.tar.gz s3://$S3_BUCKET/$STACK/PROJ/
    fi
}