FROM heroku/heroku:18-build

RUN apt-get -q update
RUN apt-get -q -y --no-install-recommends install \
    awscli \
    libkml-dev

ADD . /heroku-geo-buildpack

WORKDIR "/heroku-geo-buildpack/builds"
