name: CI

on:
  push:
    # Avoid duplicate builds on PRs.
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck
        run: shellcheck --check-sourced --color=always bin/* builds/*.sh tests.sh

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack_version: ["20", "22"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: make test STACK_VERSION='${{ matrix.stack_version }}'
